"""initial schema

Revision ID: a4146a81884f
Revises: 
Create Date: 2026-09-15 14:59:13.030532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4146a81884f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='member_status'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('father_or_husband', sa.String(length=255), nullable=False),
    sa.Column('mother', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=32), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('nid', sa.String(length=64), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('whatsapp', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('urgent_contact_name', sa.String(length=255), nullable=True),
    sa.Column('urgent_contact_relation', sa.String(length=128), nullable=True),
    sa.Column('urgent_contact_mobile', sa.String(length=32), nullable=True),
    sa.Column('urgent_contact_address', sa.Text(), nullable=True),
    sa.Column('admission_fee', sa.String(length=32), nullable=False),
    sa.Column('subscription', sa.String(length=32), nullable=False),
    sa.Column('receipt_no', sa.String(length=64), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('member_signature', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.String(length=32), nullable=False),
    sa.Column('member_photo_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=True)
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DUE', 'PAID', name='installment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_member_credentials_username'), 'member_credentials', ['username'], unique=True)
    op.create_table('nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.JSON(), nullable=False),
    sa.Column('property_type_other', sa.String(length=255), nullable=True),
    sa.Column('khatian_no', sa.String(length=128), nullable=True),
    sa.Column('dag_no_cs', sa.String(length=128), nullable=True),
    sa.Column('dag_no_rs', sa.String(length=128), nullable=True),
    sa.Column('land_quantity', sa.String(length=128), nullable=True),
    sa.Column('ownership', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicable_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_phone', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('co_owners')
    op.drop_table('applicable_docs')
    op.drop_table('properties')
    op.drop_table('nominees')
    op.drop_index(op.f('ix_member_credentials_username'), table_name='member_credentials')
    op.drop_table('member_credentials')
    op.drop_table('installments')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
